//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutritionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nutrition
    {
        public int Id { get; set; }
        public string Categorie { get; set; }
        public string Nume { get; set; }
        public int kCal { get; set; }
        public int Proteine { get; set; }
        public int Glucide { get; set; }
        public int Lipide { get; set; }
        public int Fibre { get; set; }
    }
}
