//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutritionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nutrition
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public string Name { get; set; }
        public int kCal { get; set; }
        public int Proteins { get; set; }
        public int Glucides { get; set; }
        public int Fats { get; set; }
        public int Carbrohydrates { get; set; }
    }
}
